defaults:
  - _self_

base_path: "./test_results"
ground_truth_csv: "ground_truth.csv"
output_csv: "output_metrics.csv"
model_names:
  - "yolov5n"
  - "yolov5s"
  - "yolov5m"
  - "yolov5x"
  - "yolov10n"
  - "yolov10s"
  - "yolov10m"
  - "yolov10b"
  - "yolov10l"
  - "yolov10x"