dataset:
  dataset_type: CrowdHuman
  files_to_download:
    CrowdHuman_train01.zip: "https://drive.google.com/uc?id=134QOvaatwKdy0iIeNqA_p-xkAhkV4F8Y"
    CrowdHuman_train02.zip: "https://drive.google.com/uc?id=17evzPh7gc1JBNvnW1ENXLy5Kr4Q_Nnla"
    CrowdHuman_train03.zip: "https://drive.google.com/uc?id=1tdp0UCgxrqy1B6p8LkR-Iy0aIJ8l4fJW"
    CrowdHuman_val.zip: "https://drive.google.com/uc?id=18jFI789CoHTppQ7vmRSFEdnGaSQZ4YzO"
    annotation_train.odgt: "https://drive.google.com/uc?id=1UUTea5mYqvlUObsC1Z8CFldHJAtLtMX3"
    annotation_val.odgt: "https://drive.google.com/uc?id=10WIRwu8ju8GRLuCkZ_vT6hnNxs5ptwoL"
  data_dir: "./crowdhuman"
  annotations_dir: "./crowdhuman/annotations"
  image_dir: "./crowdhuman/Images"
  annotations_file: "./crowdhuman/annotation_train.odgt"